image: docker:latest

services:
  - docker:dind
  
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B -DskipTests"
  artifacts:
    paths:
      - target/*.jar
  
build-master:
  stage: package
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker images
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker logout
  only:
    - master
    
deploy-production:
  image: debian:latest
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - echo "$SSH_PROD_PKEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  stage: deploy
  environment: Production
  only: 
    - master  
  script:
    - ssh -p $SSH_PROD_PORT $SSH_PROD_USER@$SSH_PROD_HOST