image: docker:latest

services:
- docker:dind

stages:
- build

build:
  stage: build
  script:
  - docker build . -t hoohoot/synapse-keycloak-adapter
  - docker images
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - docker push hoohoot/synapse-keycloak-adapter
  - docker logout
