version: '2'

services:
  keycloak-adapter:
    build: .
    environment:
    - SYNAPSE_HOST="chat.example.org"
    - KEYCLOAK_HOST="auth.example.org"
    - REALM=testing;
    - KEYCLOAK_CLIENT_ID=my_client_id
    - KEYCLOAK_CLIENT_SECRET=my_client_secret
    ports:
    - 8480:8080
