version: '2'

services:
  keycloak-adapter:
    build: .
    environment:
    - SYNAPSE_HOST="chat.example.org"
    - KEYCLOAK_CLIENT_URI="/auth/realms/testing/protocol/openid-connect/token"
    - KEYCLOAK_CLIENT_BASIC="Basic lkjljdskjlkjdsflkjfds="
    - KEYCLOAK_HOST="auth.example.org"
    ports:
    - 8480:8080
