version: '2.1'

services:
  synapse:
    build: ./synapse
    restart: unless-stopped
    environment:
    - SYNAPSE_SERVER_NAME=chat.hoohoot.org
    - SYNAPSE_REPORT_STATS=no
    - SYNAPSE_ENABLE_REGISTRATION=no
    - SYNAPSE_LOG_LEVEL=INFO
    - POSTGRES_PASSWORD=XXgp3Cp61J4xwT1H
    - SYNAPSE_NO_TLS=yes
    - SYNAPSE_CONFIG_PATH=/data/server_config
    volumes:
    - synapse:/data
    - ./synapse/server_config:/data/server_config
    depends_on:
      db:
        condition: service_healthy
    ports:
    - 8008:8008/tcp

  db:
    image: postgres:10-alpine
    environment:
    - POSTGRES_USER=synapse
    - POSTGRES_PASSWORD=XXgp3Cp61J4xwT1H
    volumes:
    - postgres:/var/lib/postgresql/data

  mxisd:
    image: kamax/mxisd
    restart: unless-stopped
    volumes:
    - mxisd:/var/mxisd
    - ./mxisd/mxisd.yaml:/etc/mxisd/mxisd.yaml
    ports:
    - 8090:8090

  keycloak-adapter:
    image: hoohoot/synapse-keycloak-adapter:latest
    restart: unless-stopped
    ports:
    - 8480:8080
    environment:
    - KEYCLOAK_HOST="auth.example.org"
    - SYNAPSE_HOST="auth.example.org";
    - REALM=testing;
    - KEYCLOAK_CLIENT_ID=my_client_id
    - KEYCLOAK_CLIENT_SECRET=my_client_secret
    - KEYCLOAK_SEARCH_PASSWORD=password

  riot:
    build: ./riot
    restart: unless-stopped
    ports:
    - 8009:8009
    depends_on:
      synapse:
        condition: service_started

volumes:
  synapse:
  postgres:
  mxisd:
